# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d22166e76f35ba56f31cbb70b642c6a10a02878cf96a1bddfab32acb14ca7620410eb56045d9f1153a78715310c378b4e351f0f5ace3cd49eba3ff2fdcf80b

test:
  secret_key_base: 93d3f2c5674c6d97ed11b78c20c4aa1eaa2cca3341491c82750a5a908078c87c3f89f62d8c05cb10962abfece7fbf05272f9fde4a35eb3501822207750198edc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
